language: node_js
node_js: "12.1.0"
before_script:
  - "export NODE_ENV=production"
  - "yarn run build:localFileManifest"
script: "yarn run build:prod"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master